config/routes.rb
Rails.application.routes.draw do 

  namespace :admin do
    resources :accounts
    resources :logs
    resource :companies
    resources :organizations
    resources :image_links
    resources :group_banners
    resources :scientific_banners
    resources :settings do
      collection do
        post :clear_home_bg
      end
    end
    resources :links
    resources :articles do
      collection do
        post :images
      end
    end
    resources :article_categories do
      post :update_nav
    end
    resources :swipers
    resources :navigation_bars
    root to: redirect("admin/dashboard/show")
    get 'dashboard/show'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'welcome/index'
  root 'welcome#index'
  resources :categories, only: [:show]
  resources :organizations
  resources :articles, only: [:index, :show]
  resources :office, only: [:show]
  resources :links, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :article_category
  validates :title, :content, :article_category_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  acts_as_nested_set
  validates :name, presence: true

  has_many :articles
end

app/models/group_banner.rb
class GroupBanner < ApplicationRecord
  mount_uploader :path, ArticleUploader
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ArticleUploader
end

app/models/image_link.rb
class ImageLink < ApplicationRecord
  mount_uploader :path, ArticleUploader
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/navigation_bar.rb
class NavigationBar < ApplicationRecord
    acts_as_list top_of_list: 0
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/scientific_banner.rb
class ScientificBanner < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
  mount_uploader :logo, SettingUploader
  mount_uploader :qrcode, SettingUploader
  mount_uploader :home_bg, SettingUploader
end

app/models/swiper.rb
class Swiper < ApplicationRecord
  mount_uploader :url, SwiperUploader

  validates :title, :url, presence: true
  # validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :logs
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :page_header

  # GET /admin/articles
  # GET /admin/articles.json
  def index
    if params[:article_category_id]
      categories = ArticleCategory.find(params[:article_category_id]).self_and_descendants
      @articles = Article.where(article_category_id: categories.pluck(:id))
    
    else
      @articles = Article.all
    end
    
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.json
  def show
  end

  # GET /admin/articles/new
  def new
    @article = Article.new
  end

  # GET /admin/articles/1/edit
  def edit
  end

  # POST /admin/articles/images
  def images
    image = Image.new(file: params['image']['attachment'])
    if image.save
      Log.create(title: "上传图片", user: current_user, desc: image.file.url )
      render json: {status: 'success', url: image.file.url}
    else
      render json: {status: 'error', msg: '上传失败'}
    end
  end

  # POST /admin/articles
  # POST /admin/articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        Log.create(title: "创建 #{@article.title} %> 文章", user: current_user )
        format.html { redirect_to [:admin, @article], notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/articles/1
  # PATCH/PUT /admin/articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        Log.create(title: "更新 #{@article.title} %> 文章", user: current_user )
        format.html { redirect_to [:admin, @article], notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      Log.create(title: "删除 #{@article.title} %> 文章", user: current_user )
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :content, :brief, :article_category_id)
    end

    def page_header
      @page_header =  [
        {name: '首页', path: admin_root_path}, 
        {name: '文章管理', path: admin_articles_path, is_current: true}
      ] 
    end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def show
    @article = Article.find(params[:id])
    if @article.article_category.root.name == '科室建设'
      @category = @article.article_category.self_and_ancestors.find{|category| category.level == 1}
    else
      @category = @article.article_category.root
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def show
    @article = Article.find(params[:id])
    if @article.article_category.root.name == '科室建设'
      @category = @article.article_category.self_and_ancestors.find{|category| category.level == 1}
    else
      @category = @article.article_category.root
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end
end

app/controllers/office_controller.rb
class OfficeController < ApplicationController
  def show
    @category = ArticleCategory.find_by(id:  params[:id])
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/office_helper.rb
module OfficeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/admin/articles/_form.html.erb
<%= form_for([:admin, @article]) do |f| %>
  <%= render 'layouts/admin/errors', _models: @article %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :article_category_id %>
    <% 
      if params[:article_category_id] || action_name == 'edit'
        article_category = ArticleCategory.find(params[:article_category_id]) if params[:article_category_id]
        article_category = @article.article_category.self_and_ancestors.find { |ar| ar.level == 1 } if action_name == 'edit'
        if article_category.root.name == '科室建设'
          article_categories = [article_category.descendants.map { |k| ["#{'--' * (k.level-2)} #{k.name}", k.id] }]
          article_categories = [article_categories.unshift([article_category.name])]
        else
          # article_category.self_and_descendants.map { |k| ["#{'--' * (k.level-1)} #{k.name}", k.id] }
          article_categories = [article_category.self_and_descendants.map { |k| ["#{'--' * (k.level-1)} #{k.name}", k.id] }]
          article_categories = [article_categories.unshift([article_category.root.name])]
        end
      else
        article_categories = ArticleCategory.roots.map { |i| [[i.name], i.descendants.map { |k| ["#{'--' * (k.level-1)} #{k.name}", k.id] }]} 
      end
    %>
    <%= f.select :article_category_id, grouped_options_for_select(article_categories), {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :brief %>
    <%= f.text_area :brief, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%#= tinymce :theme => "simple", :language => "de", :plugins => ["wordcount", "paste"] %>
    <%= f.text_area :content, :class => "tinymce", :rows => 20, :cols => 60 %>
  </div>

  <div class="actions">
    <%= f.submit "提交", class: "btn btn-primary" %>
  </div>
<% end %>
<script type="text/javascript">
  tinyMCE.init({
    selector: 'textarea.tinymce',
    plugins: 'preview fullscreen code image imagetools media link lists table textcolor',
    fontsize_formats: '12px 14px 16px 18px 20px 22px 24px 26px 28px 30px',
    font_formats: 'Arial=arial,helvetica,sans-serif;  仿宋_GB2312=仿宋_GB2312;',
    toolbar: 'formatselect | fontselect |fontsizeselect | bold italic strikethrough forecolor backcolor removeformat | link image | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | fullscreen preview',
    readonly: $('textarea.tinymce').attr('readonly') == 'readonly',
    language: 'zh_CN',
    images_upload_handler: function (blobInfo, success, failure) {
      formData = new FormData();
      formData.append('image[attachment]', blobInfo.blob(), blobInfo.filename());
      $.ajax({
        type: 'POST',
        url: '/admin/articles/images',
        dataType: "json",
        data: formData,
        processData: false,
        contentType: false,
        success: function (data) {
          console.log(data)
          if (data.status == 'success') {
            console.log(data.url)
            success(data.url);
          } else {
            failure(data.msg);
          }
        },
        error: function () {
          failure('服务器繁忙，请稍后重试！');
        }
      });
    }
  });
</script>

app/views/admin/articles/edit.html.erb
<%#= render 'shared/admin/page_header', current_page: '导航列表', pages: @page_header %>
<div class="card">
  <div class="card-header">
    <h3 class="card-title">
      <%#= link_to '后退', admin_articles_path(article_category_id: @article.article_category.self_and_ancestors.find { |ar| ar.level == 1 }.id), class: "btn btn-default" %>
    </h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <%= render 'form' %>
  </div>
  <!-- /.card-body --> 
</div>

app/views/admin/articles/index.html.erb
<%= render 'shared/admin/page_header', current_page: '导航列表', pages: @page_header %>
<div class="card">
  <div class="card-header">
    <h3 class="card-title">
      <%= link_to '新增', new_admin_article_path(article_category_id: params[:article_category_id]), class: "btn btn-primary" %>
    </h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
      <table class="table table-bordered">
        <tr>
          <td width="200">分类 </td>
          <td width="220">标题 </td>
          <td>摘要 </td>
          <td width="200">创建日期 </td>
          <td width="200">更新日期 </td>
          <td width="150"></td>
        </tr>
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.article_category.name %></td>
            <td><%= article.title %></td>
            <td><%= article.brief %></td>
            <td><%= article.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
            <td><%= article.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
            <td>
              <%= link_to '显示', admin_article_path(article) %>
              <%= link_to '编辑', edit_admin_article_path(article) %>
              <%= link_to '删除', [:admin, article], method: :delete, data: { confirm: '确定删除吗?' } %>
            </td>
          </tr>
        <% end %>
      </table>
  </div>
  <!-- /.card-body --> 
</div>

app/views/admin/articles/new.html.erb
<%= render 'shared/admin/page_header', current_page: '导航列表', pages: @page_header %>
<div class="card">
  <div class="card-header">
    <h3 class="card-title">
      <%= link_to '后退', admin_articles_path(article_category_id: params[:article_category_id]), class: "btn btn-default" %>
    </h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <%= render 'form' %>
  </div>
  <!-- /.card-body --> 
</div>

app/views/admin/articles/show.html.erb
<%= render 'shared/admin/page_header', current_page: '导航列表', pages: @page_header %>
<div class="card">
  <div class="card-header">
    <h3 class="card-title">
      <%= link_to '后退', admin_articles_path(article_category_id: @article.article_category.self_and_ancestors.find { |ar| ar.level == 1 }.id), class: "btn btn-default" %> |
      <%= link_to '编辑', edit_admin_article_path(@article), class: "btn btn-primary" %>
    </h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <h3> <%= @article.title %> </h3>
    <p style="margin-bottom: 0"> <strong>作者:</strong> <%= @article.author %> </p>
    <p> <strong>分类:</strong> <%= @article.article_category.name %></p>
    <hr />
    <p><%= @article.brief %></p>
    <hr />
    <div class="content">
      <%= raw @article.content %>
    </div>
  </div>
  <!-- /.card-body --> 
</div>

app/views/articles/index.html.erb
<div class="page-right direction-column" style="padding-left: 0; border: none">
  <h2 class="group-title">
    <div> 搜索结果 </div>
  </h2>
  <ul class="article-list search">
    <% @articles.order(created_at: :desc).each do |article|%>
    <li>
      <h3> <%= link_to article.title, article_path(article) %></h3>
      <p> <%= article.brief %></p>
      <div><%= article.created_at.strftime("%Y-%m-%d")%></div>
    </li>
    <% end %>
  </ul>
</div>

app/views/articles/show.html.erb
<%= render 'layouts/left', category: @category %>
<div class="page-right direction-column">
  <h2 class="group-title">
    <div> <%= @article.title %> </div>
  </h2>
  <div class="article-content">
    <%= raw @article.content %>
  </div>
</div>