config/routes.rb
Rails.application.routes.draw do 

  namespace :admin do
    resources :accounts
    resources :logs
    resource :companies
    resources :organizations
    resources :image_links
    resources :group_banners
    resources :scientific_banners
    resources :settings do
      collection do
        post :clear_home_bg
      end
    end
    resources :links
    resources :articles do
      collection do
        post :images
      end
    end
    resources :article_categories do
      post :update_nav
    end
    resources :swipers
    resources :navigation_bars
    root to: redirect("admin/dashboard/show")
    get 'dashboard/show'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'welcome/index'
  root 'welcome#index'
  resources :categories, only: [:show]
  resources :organizations
  resources :articles, only: [:index, :show]
  resources :office, only: [:show]
  resources :links, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :article_category
  validates :title, :content, :article_category_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  acts_as_nested_set
  validates :name, presence: true

  has_many :articles
end

app/models/group_banner.rb
class GroupBanner < ApplicationRecord
  mount_uploader :path, ArticleUploader
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ArticleUploader
end

app/models/image_link.rb
class ImageLink < ApplicationRecord
  mount_uploader :path, ArticleUploader
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/navigation_bar.rb
class NavigationBar < ApplicationRecord
    acts_as_list top_of_list: 0
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/scientific_banner.rb
class ScientificBanner < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
  mount_uploader :logo, SettingUploader
  mount_uploader :qrcode, SettingUploader
  mount_uploader :home_bg, SettingUploader
end

app/models/swiper.rb
class Swiper < ApplicationRecord
  mount_uploader :url, SwiperUploader

  validates :title, :url, presence: true
  # validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :logs
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/office_helper.rb
module OfficeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/layouts/admin/_errors.html.erb
<% if _models.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% _models.errors.full_messages.each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>
<% end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <title>国家中医药管理局监测统计中心</title>
  <!-- jQuery -->
  <script src="/plugins/jquery/jquery.min.js"></script>
  <%= javascript_include_tag    'admin/application', media: 'all' %>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="/plugins/googleapis/googleapis.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="/plugins/jqvmap/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/dist/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">
  <!-- summernote -->
  <link rel="stylesheet" href="/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed text-sm">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <%= image_tag "logo.png", class: "animation__shake" %>
    <%# <img class="" src="/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60"> %>
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light" style="justify-content: space-between;">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
    <div class="float-right">
      <%= link_to '退出', destroy_user_session_path, method: :delete %>
    </div>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <%= link_to root_path, class: 'brand-link d-flex align-items-center', target: '_blank' do %>
      <%= image_tag "admin/navLogo.png", class: "brand-image", style: "opacity: .8" %>
      <span class="brand-text font-weight-light d-block">国家中医药管理局<br>监测统计中心</span>
    <% end %>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="mt-3 mb-3 d-flex"> </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <%= link_to admin_root_path, class: 'custom-nav nav-link', data: {current: "首页"} do %>
              <%# <i class="nav-icon fas fa-tachometer-alt"></i> %>
              <p> 首页 </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_organizations_path, class: "custom-nav nav-link", data: {current: ""} do %>
              <p> 组织架构 </p>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to edit_admin_article_path(ArticleCategory.find_by(name: '首页中心简介').articles.first), class: "custom-nav nav-link", data: {current: ""} do %>
              <p> 中心简介 </p>
            <% end %>
          </li>

          <% ArticleCategory.roots.where.not(name: "中心简介").each do |category|%>
          <li class="nav-item">
            <%= link_to admin_articles_path, class: "custom-nav nav-link", data: {current: ""} do %>
              <p> <%= category.name %> <i class="right fas fa-angle-left"></i> </p>
            <% end %>
            <ul class="nav nav-treeview">
              <% category.children.each do |childre_category| %>
              <li class="nav-item">
                <%= link_to admin_articles_path(article_category_id: childre_category.id), class: "nav-link", data: {current: childre_category.name } do %>
                  <i class="far fa-circle nav-icon"></i>
                  <p><%= childre_category.name %></p>
                <% end %>
              </li>
              <% end %>
            </ul>
          </li>
          <% end %>

          <li class="nav-item">
            <%= link_to admin_swipers_path, class: "custom-nav nav-link", data: {current: "轮播图"} do %>
              <%# <i class="nav-icon far fa-image"></i> %>
              <p> 轮播图 </p>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to admin_article_categories_path, class: "custom-nav nav-link", data: {current: "分类管理"} do %>
              <%# <i class="nav-icon fas fa-ellipsis-h"></i> %>
              <p> 分类管理 </p>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to admin_group_banners_path, class: "custom-nav nav-link", data: {current: "分类管理"} do %>
              <%# <i class="nav-icon fas fa-ellipsis-h"></i> %>
              <p> 党群建设链接 </p>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to admin_scientific_banners_path, class: "custom-nav nav-link", data: {current: "分类管理"} do %>
              <%# <i class="nav-icon fas fa-ellipsis-h"></i> %>
              <p> 学术研究链接 </p>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to admin_links_path(category: 'brother'), class: "custom-nav nav-link", data: {current: "兄弟链接"} do %>
              <%# <i class="nav-icon fas fa-link"></i> %>
              <p> 兄弟链接 </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_links_path(category: 'friend'), class: "custom-nav nav-link", data: {current: "友情链接"} do %>
              <%# <i class="nav-icon fas fa-link"></i> %>
              <p> 友情链接 </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_image_links_path, class: "custom-nav nav-link", data: {current: "友情链接"} do %>
              <%# <i class="nav-icon fas fa-link"></i> %>
              <p> 数据平台 </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to edit_admin_setting_path('index'), class: "custom-nav nav-link", data: {current: "友情链接"} do %>
              <%# <i class="nav-icon fas fa-link"></i> %>
              <p> 系统设置 </p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to edit_user_registration_path, class: "custom-nav nav-link", data: {current: "修改密码"} do %>
              <%# <i class="nav-icon fas fa-link"></i> %>
              <p> 修改密码 </p>
            <% end %>
          </li>

          <!-- <li class="nav-item"> -->
            <%#= link_to admin_accounts_path, class: "custom-nav nav-link", data: {current: "管理员列表"} do %>
              <%# <i class="nav-icon fas fa-link"></i> %>
              <!-- <p> 管理员列表 </p> -->
            <%# end %>
          <!-- </li> -->
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <% if content_for?(:page_header) %>
      <%= yield(:page_header) %>
    <% else %>
      <div style="height: 30px;"> </div>
    <% end %>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <%= yield %>
        
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <%# <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer> %>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery UI 1.11.4 -->
<script src="/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/plugins/moment/moment.min.js"></script>
<script src="/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<% if controller_name == 'dashboard' %>
  <script src="/dist/js/pages/dashboard.js"></script>
<% end %>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/plugins/jquery-treetable/jquery.treetable.js"></script>
</body>
</html>

app/views/layouts/admin/session.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>国家中医药管理局监测统计中心</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="/plugins/googleapis/googleapis.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
<%= yield %>

<!-- jQuery -->
<script src="/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.min.js"></script>
</body>
</html>