config/routes.rb
Rails.application.routes.draw do 

  namespace :admin do
    resources :accounts
    resources :logs
    resource :companies
    resources :organizations
    resources :image_links
    resources :group_banners
    resources :scientific_banners
    resources :settings do
      collection do
        post :clear_home_bg
      end
    end
    resources :links
    resources :articles do
      collection do
        post :images
      end
    end
    resources :article_categories do
      post :update_nav
    end
    resources :swipers
    resources :navigation_bars
    root to: redirect("admin/dashboard/show")
    get 'dashboard/show'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'welcome/index'
  root 'welcome#index'
  resources :categories, only: [:show]
  resources :organizations
  resources :articles, only: [:index, :show]
  resources :office, only: [:show]
  resources :links, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :article_category
  validates :title, :content, :article_category_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  acts_as_nested_set
  validates :name, presence: true

  has_many :articles
end

app/models/group_banner.rb
class GroupBanner < ApplicationRecord
  mount_uploader :path, ArticleUploader
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ArticleUploader
end

app/models/image_link.rb
class ImageLink < ApplicationRecord
  mount_uploader :path, ArticleUploader
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/navigation_bar.rb
class NavigationBar < ApplicationRecord
    acts_as_list top_of_list: 0
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/scientific_banner.rb
class ScientificBanner < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
  mount_uploader :logo, SettingUploader
  mount_uploader :qrcode, SettingUploader
  mount_uploader :home_bg, SettingUploader
end

app/models/swiper.rb
class Swiper < ApplicationRecord
  mount_uploader :url, SwiperUploader

  validates :title, :url, presence: true
  # validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :logs
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @news = ArticleCategory.find_by(custom_key: '新闻')
    @articles = Article.where(article_category_id: @news.descendants.pluck(:id)).limit(3).order(created_at: :desc)
    @office_build = ArticleCategory.find_by(custom_key: '科室建设')

    # p Dir.entries(Rails.public_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/office_helper.rb
module OfficeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/welcome/index.html.erb
<% if Swiper.where(category: 'big').present? %>
<div style="width: 100%; height: 542px; margin-bottom: 20px; position: relative;">
  <div
    style="--swiper-navigation-color: #fff; --swiper-pagination-color: #fff"
    class="swiper mySwiper2"
  >
    <div class="swiper-wrapper">
      <% Swiper.where(category: 'big').order(position: :desc).each do |swiper| %>
      <div class="swiper-slide">
        <%= link_to swiper.link do %>
          <%= image_tag swiper.url.url %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  <div thumbsSlider="" class="swiper mySwiper">
    <div class="swiper-wrapper">
      <% Swiper.where(category: 'big').order(position: :desc).each do |swiper| %>
      <div class="swiper-slide">
        <%= swiper.title %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>
<div class="direction-row">
  <div class="news-swiper">
    <div class="swiper-wrapper">
      <% Swiper.where(category: ['', 'small']).order(position: :desc).each do |swiper| %>
      <div class="swiper-slide">
        <%= link_to swiper.link do %>
          <%= image_tag swiper.url.url %>
        <% end %>
        <div class="swiper-item-title"><p><%= swiper.title %></p></div>
      </div>
      <% end %>
    </div>
    <div class="swiper-pagination"></div>
  </div>

  <div class="direction-column flex-item" style="margin-left: 40px;">
    <div class="news-loop direction-column">
      <h2 class="group-title">
        <div class="hover-cateory">
          <% @news.descendants.each_with_index do |c,index| %>
            <span class="<%= 'current' if index == 0 %>" style="cursor: pointer;"><%= c.name %></span>
          <% end %>
        </div>
        <%= link_to '更多', category_path(@news) %>
      </h2>
      <% @news.descendants.each_with_index do |c,index| %>
      <div class="direction-column news-list" style="<%= 'display: none;' if index != 0 %>">
        <% Article.where(article_category_id: c.id).limit(3).order(created_at: :desc).each do |article| %>
        <dl>
          <dt>
            <%= link_to article_path(article) do %>
              <%= article.title %> <%= article.created_at.strftime("%Y-%m-%d")%>
            <% end %>
          </dt>
        </dl>
        <% end %>
      </div>
      <% end %>
    </div>
    <div class="center direction-column">
      <h2 class="group-title"> 中心简介 </h2>
      <div class="satcm-content">
        <%= ArticleCategory.find_by(name: '首页中心简介').articles.first.brief %>
      </div>
    </div>
  </div>
</div>
<div class="hr"></div>
<div class="direction-column">
  <h2 class="group-title"> 科室建设 </h2>
  <div class="department">
    <div class="item-list" style="justify-content: space-around;">

      <%
        keys = ["战略规划处", "政策研究处", "综合统计处", "信息化建设处", "医疗服务评价处", "健康医疗大数据处", "专项调查处", "项目监管处"]
        keys.map{|name| ArticleCategory.find_by(custom_key: name)}.each do |category|
      %>
        <% unless category.nil? %>
          <%= link_to category.name.html_safe, office_path(category.id) %>
        <% end %>
      <% end %>
    </div>
    <%
      office_build_articles = Article.where(article_category_id: ArticleCategory.find_by(name: '科室建设').descendants.pluck(:id)).order(created_at: :desc)
    %>
    <div class="item-news direction-column">
      <% office_build_articles.limit(3).each do |article|%>
        <%= link_to article_path(article) do %>
          <p style="display: -webkit-box; overflow: hidden; text-overflow: ellipsis; -webkit-line-clamp: 2; -webkit-box-orient: vertical;"><%= article.title %></p>
        <% end %>
      <% end %>
    </div>
    <ul class="item-link direction-column">
      <% office_build_articles.offset(3).limit(5).each do |article| %>
      <li>
        <%= link_to article_path(article) do %>
          <p>[<%= article.article_category.name -%>]</p>
          <div style="display: -webkit-box; overflow: hidden; text-overflow: ellipsis; -webkit-line-clamp: 1; -webkit-box-orient: vertical;">
            <%= truncate("#{article.created_at.strftime("%Y-%m-%d")} #{article.title}", length: 30) %>
          </div>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="direction-row" style="justify-content: space-between; margin-top: 28px;">
  <div class="welcome-left direction-column">
    <h2 class="group-title"> 党群建设 </h2>
    <% GroupBanner.all.order(position: :desc).each do |banner| %>
      <%= link_to banner.link, target: "_blank" do %>
        <%= image_tag banner.path.url, width: '100%' %>
      <% end %>
    <% end %>
    <ul class="parties-building">
      <%
        group_article = Article.where(article_category_id: ArticleCategory.find_by(name: '党群建设').descendants.pluck(:id)).order(created_at: :desc)
      %>
      <% group_article.limit(8).each do |article| %>
        <li><%= link_to truncate(article.title, length: 20), article_path(article) %></li>
      <% end %>
    </ul>
    <h2 class="group-title"> 学术研究 </h2>
    <% ScientificBanner.all.where(home_enabled: true).order(position: :desc).each do |banner| %>
      <%= link_to "#{banner.link}", target: "_blank" do %>
        <%= image_tag banner.path.url, width: '100%' %>
      <% end %>
    <% end %>
    <ul class="learning">
      <%
        study_article = Article.where(article_category_id: ArticleCategory.find_by(name: '学术研究').descendants.pluck(:id)).order(created_at: :desc)
      %>
      <% study_article.limit(8).each do |article| %>
        <li><%= link_to truncate(article.title, length: 16), article_path(article) %></li>
      <% end %>
    </ul>
  </div>
  <div class="welcome-right direction-column">
    <h2 class="group-title"> 信息发布 </h2>
      <%
        message = ArticleCategory.find_by(name: '信息发布').descendants
      %>
      <% message.limit(3).each do |category| %>
        <dl class="notice">
          <dt><%= category.name %></dt>
          <dd>
            <% category.articles.limit(4).order(created_at: :desc).each do |article| %>
              <%= link_to article.title, article_path(article) %>
            <% end %>
          </dd>
        </dl>
      <% end %>
    <h2 class="group-title"> 数据平台 </h2>
    <ul>
      <% ImageLink.all.order(position: :desc).each do |il| %>
      <li>
        <%= link_to il.link, target: "_blank" do %>
          <%= image_tag il.path.url, width: "100%" %>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<%= content_for :script do %>
<script type="text/javascript">

  $(document).ready(function() {
    $(".hover-cateory span").click(function() {
      $(".news-list").hide();
      $(".news-list").eq($(this).index()).css('display','flex')
      $(this).addClass('current').siblings('span').removeClass("current")
    })
    new Swiper('.news-swiper',{
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      autoplay: {
        delay: 10000, //10秒切换一次
      },
    });
    var swiper = new Swiper(".mySwiper", {
      spaceBetween: 10,
      slidesPerView: 6,
      freeMode: true,
      direction : 'vertical',
      watchSlidesProgress: true,
      autoplay: {
        delay: 2000, //10秒切换一次
      }
    });
    var swiper2 = new Swiper(".mySwiper2", {
      spaceBetween: 10,
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
      thumbs: {
        swiper: swiper,
      },
      autoplay: {
        delay: 2000, //10秒切换一次
      }
    });
  });
</script>
<% end %>
<style>
  .mySwiper2 {
    width:  100%;
    height: 542px;
    overflow: hidden;
  }
  .mySwiper {
    background: rgba(0, 0, 0, 0.4);
    width: 40%;
    height:  542px;
    box-sizing: border-box;
    padding: 10px 0;
    overflow: hidden;
    position: absolute;
    right:  0;
    top:  0;
    z-index: 10;
  }

  .mySwiper .swiper-slide {
    width: 95%;
    color: #FFF;
    padding: 10px 10px;
    box-sizing: border-box;
    line-height: 1.5;
  }
  .mySwiper .swiper-slide:hover{
    cursor: pointer;
    background-image: linear-gradient(to right, rgba(191, 6, 20, 1) 0% , rgba(191, 6, 20, 0) 100%);
    font-weight: bold;
  }
  .mySwiper .swiper-slide-thumb-active {
   background-image: linear-gradient(to right, rgba(191, 6, 20, 1) 0% , rgba(191, 6, 20, 0) 100%);
  }
  .swiper-slide a {
    display: block;
    width: 100%;
    height: 100%;
  }
  .swiper-slide img {
    display: block;
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
</style>