config/routes.rb
Rails.application.routes.draw do 

  namespace :admin do
    resources :accounts
    resources :logs
    resource :companies
    resources :organizations
    resources :image_links
    resources :group_banners
    resources :scientific_banners
    resources :settings do
      collection do
        post :clear_home_bg
      end
    end
    resources :links
    resources :articles do
      collection do
        post :images
      end
    end
    resources :article_categories do
      post :update_nav
    end
    resources :swipers
    resources :navigation_bars
    root to: redirect("admin/dashboard/show")
    get 'dashboard/show'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'welcome/index'
  root 'welcome#index'
  resources :categories, only: [:show]
  resources :organizations
  resources :articles, only: [:index, :show]
  resources :office, only: [:show]
  resources :links, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :article_category
  validates :title, :content, :article_category_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  acts_as_nested_set
  validates :name, presence: true

  has_many :articles
end

app/models/group_banner.rb
class GroupBanner < ApplicationRecord
  mount_uploader :path, ArticleUploader
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ArticleUploader
end

app/models/image_link.rb
class ImageLink < ApplicationRecord
  mount_uploader :path, ArticleUploader
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/navigation_bar.rb
class NavigationBar < ApplicationRecord
    acts_as_list top_of_list: 0
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/scientific_banner.rb
class ScientificBanner < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
  mount_uploader :logo, SettingUploader
  mount_uploader :qrcode, SettingUploader
  mount_uploader :home_bg, SettingUploader
end

app/models/swiper.rb
class Swiper < ApplicationRecord
  mount_uploader :url, SwiperUploader

  validates :title, :url, presence: true
  # validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :logs
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy, :clear_home_bg]
  before_action :page_header, except: [:clear_home_bg]

  # GET /admin/settings
  # GET /admin/settings.json
  def index
    @settings = Setting.all
  end

  # GET /admin/settings/1
  # GET /admin/settings/1.json
  def show
    
  end

  # GET /admin/settings/new
  def new
    @setting = Setting.new
  end

  # GET /admin/settings/1/edit
  def edit
  end

  # POST /admin/settings
  # POST /admin/settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save

        format.html { redirect_to [:admin, @setting, 'index'], notice: 'Setting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @setting }
      else
        format.html { render action: 'new' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def clear_home_bg
    @setting.update(home_bg: nil)
    redirect_to edit_admin_setting_path(@setting.id)
  end

  # PATCH/PUT /admin/settings/1
  # PATCH/PUT /admin/settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        Log.create(title: "更新设置", user: current_user)
        format.html { redirect_to  [:edit, :admin, @setting], notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.first
      Setting.create unless @setting
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:logo, :tel, :address, :qrcode, :oa_path, :title, :description, :keywords, :icp, :email, :home_bg)
    end

    def page_header
      @page_header =  [
        {name: '首页', path: admin_root_path}, 
        {name: '系统设置', path: edit_admin_setting_path, is_current: true}
      ] 
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end
end

app/controllers/office_controller.rb
class OfficeController < ApplicationController
  def show
    @category = ArticleCategory.find_by(id:  params[:id])
  end
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/office_helper.rb
module OfficeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/admin/settings/_form.html.erb
<%= form_for([:admin, @setting]) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :keywords %>
    <%= f.text_field :keywords, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :logo %>
    <br />
    <%= image_tag @setting.logo.url, height: '40' unless @setting.logo.blank? %>
    <%= f.file_field :logo, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :home_bg %>
    <br />
    <% unless @setting.home_bg.blank? %>
      <%= image_tag @setting.home_bg.url, height: '40' %>
      <%= link_to '清空背景', clear_home_bg_admin_settings_path, method: :post%>
    <% end %>
    <%= f.file_field :home_bg, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :tel %>
    <%= f.text_field :tel, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :icp %>
    <%= f.text_field :icp, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :qrcode %>
    <br />
    <%= image_tag @setting.qrcode.url, height: '40' unless @setting.qrcode.blank? %>
    <%= f.file_field :qrcode, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :oa_path %>
    <%= f.text_field :oa_path, class: 'form-control'  %>
  </div>
  <div class="actions">
    <%= f.submit "提交", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/settings/edit.html.erb
<%= render 'shared/admin/page_header', current_page: '修改分类', pages: @page_header %>
<div class="card">
  <!-- /.card-header -->
  <div class="card-body">
      <%= render 'form' %>
  </div>
  <!-- /.card-body --> 
</div>

app/views/admin/settings/index.html.erb
<h1>Listing settings</h1>

<table>
  <thead>
    <tr>
      <th>Logo</th>
      <th>Tel</th>
      <th>Address</th>
      <th>Qrcode</th>
      <th>Banner a</th>
      <th>Banner b</th>
      <th>Oa path</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.logo %></td>
        <td><%= setting.tel %></td>
        <td><%= setting.address %></td>
        <td><%= setting.qrcode %></td>
        <td><%= setting.oa_path %></td>
        <td><%= link_to 'Show', [:admin, setting] %></td>
        <td><%= link_to 'Edit', edit_admin_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', [:admin, setting], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_admin_setting_path %>

app/views/admin/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logo:</strong>
  <%= @setting.logo %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @setting.tel %>
</p>

<p>
  <strong>Address:</strong>
  <%= @setting.address %>
</p>

<p>
  <strong>Qrcode:</strong>
  <%= @setting.qrcode %>
</p>

<p>
  <strong>Oa path:</strong>
  <%= @setting.oa_path %>
</p>

<%= link_to 'Edit', edit_admin_setting_path(@setting) %> |
<%= link_to 'Back', admin_settings_path %>